run:
  deadline: 5m

linters:
  enable-all: true
  disable:
    - cyclop # checks function and package cyclomatic complexity
    - deadcode # deprecated
    - depguard # Go linter that checks if package imports are in a list of acceptable packages
    - exhaustive # check exhaustiveness of enum switch statements
    - exhaustivestruct # Checks if all struct's fields are initialized
    - exhaustruct # finds structures with uninitialized fields
    - forbidigo # Forbids identifiers
    - gci # control golang package import order and make it always deterministic
    - gochecknoglobals # check that no global variables exist
    - gochecknoinits # Checks that no init functions are present in Go code
    - godox # Tool for detection of FIXME, TODO and other comment keywords
    - gofumpt # checks whether code was gofumpt-ed
    - golint # deprecated and replaced by revive
    - gomnd # An analyzer to detect magic numbers
    - gosec # Inspects source code for security problems
    - ifshort # deprecated
    - interfacebloat # checks the number of methods inside an interface
    - interfacer # deprecated suggests narrower interface types
    - ireturn # Accept Interfaces, Return Concrete Types
    - lll # Reports long lines
    - maligned # Tool to detect Go structs that would take less memory if their fields were sorted
    - nlreturn # checks for a new line before return and branch statements to increase code clarity
    - nolintlint # Reports ill-formed or insufficient nolint directives
    - nosnakecase # deprecated
    - paralleltest # detects missing usage of t.Parallel() method in your Go test
    - scopelint # deprecated and replaced by exportloopref
    - structcheck # deprecated
    - tagliatelle # Checks the struct tags naming style
    - testpackage # linter that makes you use a separate _test package
    - varcheck # deprecated
    - varnamelen # checks that the length of a variable's name matches its scope
    - wrapcheck # Checks that errors returned from external packages are wrapped
    - wsl # Whitespace Linter - Forces you to use empty lines

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - goerr113
      text: "do not define dynamic errors"
